version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
      - /home/mongodb/database:/data/mongodb
    ports:
      - 27017:27017
    expose:
      - 27017
